name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        persist-credentials: false
        
    - name: Restore dependencies
      run: dotnet restore ./Algorithms      
    - name: Build
      run: dotnet build --no-restore --configuration Release ./Algorithms
  


    - name: Test
      run: dotnet test --verbosity normal --logger "liquid.md" ./Algorithms.Tests    


    
    - name: Run Benchmark
      run: dotnet run --configuration Release --all --artifacts ./Algorithms/BenchmarkDotNet.Artifacts --project ./Algorithms
      
      
      
      
    - name: Copy result files
      run: |
        cp -f BenchmarkDotNet.Artifacts/results/*.md ./TestResults/Benchmark
        cp -f ./Algorithms.Tests/TestResults/*.md ./TestResults/UnitTests
        
    - name: Push results to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add ./TestResults/ -f
        git commit -m "Updating Tests and Benchmarks"
        git push
