name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        persist-credentials: false
        
    - name: Restore dependencies
      run: dotnet restore ./Algorithms
      
    - name: Build
      run: dotnet build --no-restore --configuration Release ./Algorithms
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        persist-credentials: false
        
    - name: Test
      run: dotnet test --verbosity normal --logger "liquid.md" ./Algorithms.Tests    
    
    - name: Copy result files
      run: cp -f ./Algorithms.Tests/TestResults/*.md ./TestResults/UnitTests
      
    - name: Push results to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add ./TestResults/
        git commit -m "Updating Unit Tests"
        git push
        
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        persist-credentials: false
        
    - name: Run Benchmark
      run: dotnet run --configuration Release --all --artifacts ./Algorithms/BenchmarkDotNet.Artifacts --project ./Algorithms
      
    - name: Copy result files
      run: cp -f ./Algorithms/BenchmarkDotNet.Artifacts/results/*.md ./TestResults/Benchmark
      
    - name: Push results to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add ./TestResults/
        git commit -m "Updating Benchmarks"
        git push
