name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        persist-credentials: false
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Benchmark
      run: dotnet run --configuration Release --all
  
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Run Benchmark
      run: dotnet run --configuration Release --all --artifacts .\BenchmarkDotNet.Artifacts\
      
    - name: Push results to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add .\BenchmarkDotNet.Artifacts\results\*.md
        git commit -m "Updating Benchmarks"
        git push
